### ISSUE TITLE
Post to #tfti when certain players are spotted for the first time in a day

### ISSUE THREAD

**Issue by ricky-wong** [korisya/kensaku#13]
```
// Special players
const tftiPlayers = [
  51448180, // RCKYWONG
  51415530, // T3ALIZES
  51400807, // MEGUMIN
];
```
When any of these players are spotted for the first time in a day, expose them in #tfti

**Comment by winber2** [comment]
expose me 2 pls

**Comment by ricky-wong** [comment]
Added in 1e38608, though the bot should automatically react, too.

**Comment by ricky-wong** [comment]
Also mention/link the channel

https://stackoverflow.com/questions/49353929/how-do-i-get-a-bot-to-mention-a-channel/49354078#49354078

**Comment by ricky-wong** [comment]
Added react in 512557e, still need to mention/link the channel, and perhaps refactor `pingChannel` to send a different `TFTI` emoji per server.
